### ISSUE TITLE
Option to only create terraform configuration without direct state import

### ISSUE THREAD

**Issue by Joerg-L** [Azure/aztfy#101]
Hey there,
I wthink it would be helpfull to split the creation of the configuration from the import into the status.

So the "switch" should lead tothat
- `main.tf` is created
- `terraform import` script is created to run all the imports manually

That would help to
- just get the configuration of of running azure environment to terraform
- review the terrafrom configuration for example by checkov/tflint etc
- update the configuration manually on the names in the main.tf file
- replace genereiv name on the import filr by search/replace with the correct naming

What do you think?
Joerg

**Comment by magodo** [comment]
@Joerg-L Thank you for this advice, it totally makes sense from a user's perspective. Unfortunately, the generation of the `main.tf` depends on the imported state. Under the hood, `aztfy` runs https://github.com/magodo/tfadd to convert the state into config. That said, we are not able to only generate the config without importing.

For naming resources, this is already something can be done via the interactive UI, or by saving the resource mapping file out, then manually edit it and run `aztfy` again with the file.

**Comment by Joerg-L** [comment]
@magodo thanks for the clarification. I think that isse can then be closed.
