### ISSUE TITLE
unattended usage of aztfy

### ISSUE THREAD

**Issue by Joerg-L** [Azure/aztfy#102]
We are aware of the fact, that we can use batch mode with an preexisting .aztfyResourceMapping.json, but that doesn't really help.

We have to export round about 100 resource groups with up to several hundreds of resources, which is taking really long time.
We have started locally to extended the `mapping_gen.go` to get more ressources mapped automatically, that works quite fine.

It would be really helpfull for export automation to just call aztfy with some parameters like filter (to ignore some of the identified resources automatically) and aztfy runs without any interaction or predefing mapping file to create the configuration.

**Comment by magodo** [comment]
The `aztfyResourceMapping.json` is not the same as the `mapping_gen.go`, where the former maps a specific ARM resource to TF resource address （can be manually changed by user）, and the latter maps ARM resource id pattern to a TF resource type (statically analyzed from the provider code).

The reason why we don't filter those identified resources by the `mapping_gen.go` is:
- This still allow users to chane the resource name
- The mapping might be incorrect

But yes, for your case that there wants repeat invocation on `aztfy`, and given the fact that you have maintained a solid mapping, also you don't really care about the TF resource names. Then it makes sense to ask `aztfy` to run in batch mode without the resource mapping file.
