### ISSUE TITLE
Split output into multiple files

### ISSUE THREAD

**Issue by Joerg-L** [Azure/aztfy#108]
A ressource group with hundreds of ressources in will lead to a "big" unclear main.tf.

To make the exported terraform configuration more clearer, I would suggest to split the write out into multiple output files.
As a seperator the ressource type could be used which can also be used as the name for the output file.

Examples:
- azurerm_subnet will be written to azurerm_subnet.tf
- azurerm_network_security_rule will be written to azurerm_network_security_rule
- ...

To make that behavior optional, an parameter like `--split_configuration` can be introduced.
As an "extension" of that feature, an user based "grouping" could be imagine so that the user is able to say 

> I want to put azurerm_subnet, azurerm_virtual_network, ... into the file network.tf

**Comment by magodo** [comment]
@Joerg-L I just realized this can be easily done via https://github.com/magodo/hclgrep.

For example, given you want to extract each resource type into its own cfg file, then you can use something like following:

```shell
outdir=`pwd` # change it to where ever you'd like
readarray -t resource_types < <(hclgrep -x 'resource $x $_ { @*_ }' -w x main.tf | uniq)
for rt in "${resource_types[@]}"; do
    hclgrep -x "resource $rt \$_ {@*_}" main.tf > $outdir/$rt.tf
done
```

**Comment by magodo** [comment]
I'm gonna close this issue for now, please feel free to reopen it if you have any other question.
