### ISSUE TITLE
Error while importing Key Vault: malformed resource address: azurerm_key_vault

### ISSUE THREAD

**Issue by meizenga** [Azure/aztfy#109]
Running aztfy 0.4.0 and importing a RG containing a key vault (with one secret) and a VM.

Key Vault resource type was not recognized so trying to manually select the resource type.
Selected azurerm_key_vault (through auto completion) and got this error:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/23551316/169771386-0c91596a-9e25-4c7e-b199-11d69832f5b4.png">

Same error when trying to map the secret, selected azurerm_key_vault_secret and got the same error

**Comment by magodo** [comment]
@meizenga You'll need to specify the full TF address, e.g. `azurerm_key_vault.test`.

**Comment by meizenga** [comment]
Thanks for that, it works.

I was reading the docs, and since I was in interactive mode, I only selected the resource type.
The readme is not mentioning that you should add the resource name.

Interactive Mode
In interactive mode, aztfy list all the resources resides in the specified resource group. For each resource, user is expected to input the Terraform resource type (e.g. azurerm_linux_virtual_machine).
...
