### ISSUE TITLE
aztfy don't connect to the right Azure subscription

### ISSUE THREAD

**Issue by jeremybouchet44** [Azure/aztfy#113]
I try to uses aztfy to export and import into teraform files (.tf) the resources of an resource group.

- Before to launch the `aztfy` command I executed the below commands to set the right subscription on which the resource group and its resources are located :

az login    # to connect to the Azure tenant with an account which **have contributor rights to the resource group**
az account set --subscription "Shared Infrastructure Dev/Test"    # to design the right subscription on default (Id : da2e245c-1da4-409b-9b54-81016ca9ae8f)

We can see that I well connected to the good subscription :

```
jbouchet@MY-DESKTOP:/mnt/c/_DevOps/aztfy_test_build_tf_files$ az account list --query "[?isDefault]"
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "XXXX-XXXX-XXXX-XXXX-XXXX",
    "id": "da2e245c-1da4-409b-9b54-81016ca9ae8f",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Shared Infrastructure Dev/Test",
    "state": "Enabled",
    "tenantId": "XXXX-XXXX-XXXX-XXXX-XXXX",
    "user": {
      "name": "jbouchet@DOMAIN.COM",
      "type": "user"
    }
  }
]
```

- Then I executed the command :

aztfy sandbox-training-zguerrouj-resource-group

- aztfy returned me the below error message :

```
 exporting arm template of resource group sandbox-training-zguerrouj-resource-group: POST
  https://management.azure.com/subscriptions/c4869d66-56dd-4ead-a65a-6a07eb7fec22/resourcegroups/sandbox-training-zguerrouj-resource-group/exportTemplate
  --------------------------------------------------------------------------------
  RESPONSE 404: 404 Not Found
  ERROR CODE: SubscriptionNotFound
  --------------------------------------------------------------------------------
  {
    "error": {
      "code": "SubscriptionNotFound",
      "message": "The subscription 'c4869d66-56dd-4ead-a65a-6a07eb7fec22' could not be found."
    }
  }
  --------------------------------------------------------------------------------
```

- **Question :**

Why aztfy don't works ?

And I don't understand why aztfy try to connect to the subscription "c4869d66-56dd-4ead-a65a-6a07eb7fec22", because it's not the subscription where is located my resource group and its resources.
The good subscription id is : da2e245c-1da4-409b-9b54-81016ca9ae8f

**Comment by meizenga** [comment]
I had the same, usually connected with multiple accounts and multiple subscription. 
Solved it by running `az clear` first and then `az login`

**Comment by magodo** [comment]
@jeremybouchet44 Sorry that you encountered this issue.

The subscription id comes from one of following (starts from the highest priority):
1. Command line option: `--subscription-id`
2. Env variable: `AZTFY_SUBSCRIPTION_ID`
3. Env variable: `ARM_SUBSCRIPTION_ID`
4. Output of azure cli: `az account show --query id`

Could you please check above items in your running environment?

**Comment by jeremybouchet44** [comment]
That works !!  Thanks !

With these commands the Terraform files are created :

```export ARM_SUBSCRIPTION_ID="da2e245c-1da4-409b-9b54-81016ca9ae8f"
export AZTFY_SUBSCRIPTION_ID="da2e245c-1da4-409b-9b54-81016ca9ae8f"
export ARM_CLIENT_ID="XXXX-XXXX-XXXX-XXXX-XXXX"
export ARM_CLIENT_SECRET="XXXX-XXXX-XXXX-XXXX-XXXX"
export ARM_TENANT_ID="XXXX-XXXX-XXXX-XXXX-XXXX"

az login --service-principal -u XXXX-XXXX-XXXX-XXXX-XXXX -p XXXX-XXXX-XXXX-XXXX-XXXX --tenant XXXX-XXXX-XXXX-XXXX-XXXX

aztfy sandbox-training-zguerrouj-resource-group
```
