### ISSUE TITLE
Remote state

### ISSUE THREAD

**Issue by pcg-abrown** [Azure/aztfy#117]
If running terrafy with remote state, and you run multiple times on different resource groups, will terrafy overwrite the remote state file, or append?

**Comment by magodo** [comment]
@pcg-abrown It will append to the remote state you specified, which means if there is a conflict for the resource address, the import will fail.

**Comment by pcg-abrown** [comment]
thanks - do you know if the backend storage account needs to be in the same subscription as the resources being imported?  If not, how do you get it there?

**Comment by magodo** [comment]
Not necessary. You can follow the [README](https://github.com/Azure/aztfy#remote-backend) to see how to specify the backend configs. If you want to specify the remote backend that is in different subscription/tenant, you can specify the `subscription_id` and `tenant_id` as is mentioned in https://www.terraform.io/language/settings/backends/azurerm#subscription_id

**Comment by magodo** [comment]
Close this issue for now as remote state is already supported. Please feel free to reopen it if you still have questions.
