### ISSUE TITLE
Odd issue while exporting the resource group

### ISSUE THREAD

**Issue by tomilaakkonen** [Azure/aztfy#119]
Not sure if this is an issue with my local setup, but Azure CLI seems to be working fine, so writing here:

I have logged in using `az login` and then set the subscription context with `az account set --subscription="id here"`. I have confirmed that the context is correct after this one with `az account show`, so I assume that Azure CLI is fine.

Then I try to run `aztfy resourcegroupname`, and it tries to fetch the resources, and I get this error message:

`
exporting arm template of resource group resourcegroupname: DefaultAzureCredential: failed to acquire a token.
  Attempted credentials:
        EnvironmentCredential: missing environment variable AZURE_TENANT_ID
        ManagedIdentityCredential: IMDS token request timed out
        AzureCLICredential: exec: "cmd.exe": executable file not found in %PATH%
`

Is there a way to run this in debug mode? I assume some REST API calls drop with tenant ID missing, but Azure CLI seems to be okay.

E: Also, rgp ARM export works with Azure CLI fine in the same session.

**Comment by magodo** [comment]
@tomilaakkonen As the error indicated, the `AzureCLICredential` failed with *exec: "cmd.exe": executable file not found in %PATH%*.

This should not be a precondition to run `aztfy`, therefore I've filed a PR to fix it in the underlying SDK: https://github.com/Azure/azure-sdk-for-go/pull/18266. While before the PR is merged, please ensure `cmd.exe` is available in your %PATH%.

**Comment by magodo** [comment]
@tomilaakkonen Sorry for a mistake, the error indicates that `az` is not in your PATH. Can you elaborate more on the scenario motivating this? Is it not feasible to set the path?

**Comment by tomilaakkonen** [comment]
@magodo Adding cmd to path did the trick

**Comment by magodo** [comment]
@tomilaakkonen Just to be sure, do you mean adding `cmd.exe` to path or `az` to path (I'm assuming the latter one)?

**Comment by tomilaakkonen** [comment]
@magodo cmd.exe (system32 folder)

**Comment by magodo** [comment]
@tomilaakkonen people reviewing the https://github.com/Azure/azure-sdk-for-go/pull/18266#issuecomment-1142267648 are wondering how does `cmd.exe` not in the PATH, would you mind tell the details?

**Comment by tomilaakkonen** [comment]
@magodo To be honest, I don't know, I haven't touched the setting ever and I also thought that it should be there so I assumed some REST calls dropped and it didn't get tenant ID because of it.
