### ISSUE TITLE
Linux Installation

### ISSUE THREAD

**Issue by kevinevans1** [Azure/aztfy#121]
Hello 

Are you able to provide instructions on how to deploy aztfy into ubuntu or fedora packages? 

This would also be beneficial for installation for WSL :) 

Thanks

Kevin

**Comment by magodo** [comment]
@kevinevans1 There is already an issue tracking the installer on the major platforms: #143. Would you please keep track on that issue for any progress? For now, I'm going to close this in favor of #143.
