### ISSUE TITLE
Aztfy not importing VM

### ISSUE THREAD

**Issue by justPaulo** [Azure/aztfy#122]
Is there any special reason why Azure resources like Virtual Machines are not imported? Googled around and found more people with the same issue. There's even an automatically generated comment in the created code, example:

...
  depends_on = [
    # Depending on "/subscriptions/xxxxxxxxx/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines/vm", **which is not imported by Terraform.**
  ]
...

**Comment by magodo** [comment]
@justPaulo This is due to currently given the resource id of a VM, `aztfy` is able to detect whether you want to import it as a `azurerm_linux_virtual_machine`, `azurerm_windows_virtual_machine` or `azurerm_virtual_machine`. Therefore, users are expected to type the resource type for it. This will be improved in a later version, where it will call  Azure API to determine the type.

**Comment by justPaulo** [comment]
Hello @magodo 
Thank you for your answer.
Unfortunately, I don't quite get it because unlike other GitHub tools like az2tf or terraformer where the VM resource types are indeed imported, regardless they are Linux or Windows VMs,  I don't see it happen with aztfy. Also unlike the mentioned tools, I don't see how to specify the import of a specific Azure resource like a VM, example:
"terraformer import azure -r <<theResourceGroup>> -R virtual_machine"
Is there any equivalent under aztfy?
And when you say "..._aztfy is able to detect whether you want to import it as a azurerm_linux_virtual_machine, azurerm_windows_virtual_machine or azurerm_virtual_machine._" does this mean there's an aztfy syntax allowing to specific such a resource?

Thanks,

**Comment by magodo** [comment]
@justPaulo Sorry that is a typo, I really mean "isn't able to"... Currently, `aztfy` only works to specify a resource group and import the containing resources, if there is a VM in it, you can specify which TF type you want to import it as (azurerm_linux_virtual_machine, azurerm_windows_virtual_machine or azurerm_virtual_machine).

You can check out this blog for a live walk through: https://www.kmruddy.com/2022/terrafy-existing-azure-resources.

**Comment by magodo** [comment]
`aztfy` can auto deduce the correct VM type now (#175).
