### ISSUE TITLE
DNS and Private DNS unable to export SOA

### ISSUE THREAD

**Issue by ffribeiro** [Azure/aztfy#127]
I'm getting the following error message while trying to export the SOA record for DNS and Private DNS. Any help is really appreciated.

 ❗️/subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/dnszones/fxcloud.ca/SOA/@
    azurerm_dns_zone.res-11

❗️/subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/privateDnsZones/contoso.org/SOA/@
  │ azurerm_private_dns_zone.res-13

**Comment by magodo** [comment]
@ffribeiro In this case you can simply skip these two resources, as the SOA record is [modeled as a property of the `azurerm_dns_zone` in Terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_zone#soa_record), which means you only need to import `/subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/dnszones/fxcloud.ca` as `azurerm_dns_zone.res-x`.

**Comment by ffribeiro** [comment]
@magodo I did skip the two SOA resources and was able to export everything. However, I'm trying now to deploy the main.tf file with terrafrom apply, and I'm getting the following error message. 

│ Error: creating Network Interface: (Name "az104-04-nic0" / Resource Group "az104-04-rg1"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateIPAddressMissing" Message="Private IP address is required when privateIPAllocationMethod is Static in IP configuration /subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/networkInterfaces/az104-04-nic0/ipConfigurations/ipconfig1." Details=[]
│
│   with azurerm_network_interface.res-19,
│   on main.tf line 95, in resource "azurerm_network_interface" "res-19":
│   95: resource "azurerm_network_interface" "res-19" {
│
╵
╷
│ Error: creating Network Interface: (Name "az104-04-nic1" / Resource Group "az104-04-rg1"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateIPAddressMissing" Message="Private IP address is required when privateIPAllocationMethod is Static in IP configuration /subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/networkInterfaces/az104-04-nic1/ipConfigurations/ipconfig1." Details=[]
│
│   with azurerm_network_interface.res-20,
│   on main.tf line 111, in resource "azurerm_network_interface" "res-20":
│  111: resource "azurerm_network_interface" "res-20" {


### **Here's what I have on my main.tf file on line 95 and 111**

resource "azurerm_network_interface" "res-19" {
  location            = "centralus"
  name                = "az104-04-nic0"
  resource_group_name = "az104-04-rg1"
  ip_configuration {
    name                          = "ipconfig1"
    private_ip_address_allocation = "Static"
    public_ip_address_id          = "/subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/publicIPAddresses/az104-04-pip0"
    subnet_id                     = "/subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/virtualNetworks/az104-04-vnet1/subnets/subnet0"
  }
  depends_on = [
    azurerm_public_ip.res-3,
    azurerm_subnet.res-16,
    azurerm_network_security_group.res-1,
  ]
}
resource "azurerm_network_interface" "res-20" {
  location            = "centralus"
  name                = "az104-04-nic1"
  resource_group_name = "az104-04-rg1"
  ip_configuration {
    name                          = "ipconfig1"
    private_ip_address_allocation = "Static"
    public_ip_address_id          = "/subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/publicIPAddresses/az104-04-pip1"
    subnet_id                     = "/subscriptions/93341713-b89f-4e20-8627-8927c7269259/resourceGroups/az104-04-rg1/providers/Microsoft.Network/virtualNetworks/az104-04-vnet1/subnets/subnet1"
  }
  depends_on = [
    azurerm_public_ip.res-4,
    azurerm_subnet.res-17,
    azurerm_network_security_group.res-1,
  ]
}

I really appreciate any help you can provide!

**Comment by magodo** [comment]
@ffribeiro This is an unfortunate issue. What you need to do is to add up the missing `private_ip_address` in the two `azurerm_network_interface` resources. You can check the value via `terraform show`.

The reason why they are missing is because they are marked as `Optional` + `Computed` in the provider schema. Currently, when `aztfy` generate config from state, it will (mostly) remove these O+C properties in order to get a valid config that can pass the `terraform validate`. As otherwise, different kinds of issues might happen (e.g. conflict properties shouldn't exist at the same time).

**Comment by magodo** [comment]
@ffribeiro There is a new CLI option called `--full-properties`, which can export all the non-computed-only attributes for the terrafied resources. That should solve your issues. But keep in mind in that case, the config probably needs manual modifications to make it valid.

I'm gonna close this issue for now, please feel free to reopen it if you have other questions.
