### ISSUE TITLE
AzureAD resources support

### ISSUE THREAD

**Issue by NissesSenap** [Azure/aztfy#129]
Hi

It would be nice to add support for AzureAD resources as well.
Especially setting up resources like azuread_application can be rather painful so any help to set it up would be really helpful.

**Comment by magodo** [comment]
@NissesSenap Thank you for this! Unfortunately, we don't have a concrete plan for supporting AzureAD, as `aztfy` currently only support importing a resource group (similar as the ARM template). Whilst, for your specific use case, you might consider using https://github.com/magodo/tfadd to generate the `azuread_application` config from state after you manually import it, via `tfadd state -full`.

**Comment by NissesSenap** [comment]
Thanks for your quick reply.
I fully understand, I might give that a try.
