### ISSUE TITLE
Windows Installer + Homebrew + Mainstream Linux

### ISSUE THREAD

**Issue by stemaMSFT** [Azure/aztfy#143]
~Can add env to PATH and installer for user friendliness for major OS scenarios~

Update(@magodo):

| **Package Manager** | **Current Status** | **Link** |
|-|-|-|
|brew|Done|https://github.com/Homebrew/homebrew-core/commits/master/Formula/aztfy.rb|
|aur|Done|https://aur.archlinux.org/packages/aztfy-bin|
|rpm|Done||
|deb|Done||
|winget|Done|https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/AzureAztfy/0.8.0|

**Comment by koudaiii** [comment]
I recently sent a pull request for Homebrew. https://github.com/Homebrew/homebrew-core/pull/104342
It is currently registered with Formulae.

```code
$ brew update 
Updated Homebrew from fe853fcb9 to 38e1af857.
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
aztfy 
```

@magodo I would add to the README, what do you think? https://github.com/Azure/aztfy#readme
I expect it will work effectively against installs like https://github.com/Azure/aztfy/issues/159.

**Comment by magodo** [comment]
@koudaiii Awesome! Thank you!

**Comment by magodo** [comment]
@stemaMSFT I've made an AUR package for `aztfy`: https://aur.archlinux.org/packages/aztfy-bin, which serves for the Arch Linux.

**Comment by koudaiii** [comment]
@magodo bump up to v0.7.0 in homebrew
https://github.com/Homebrew/homebrew-core/pull/110528

**Comment by koudaiii** [comment]
bump up to v0.8.0 in homebrew
https://github.com/Homebrew/homebrew-core/pull/112104
cc @magodo

**Comment by magodo** [comment]
@stemaMSFT I think we can close this issue now.
