### ISSUE TITLE
Aztfy not importing VMs with Azure Hybrid Benefit enabled

### ISSUE THREAD

**Issue by yukihonhk** [Azure/aztfy#152]
Aztfy does not pull in if the VM has hybrid benefit enabled on the VM

**Comment by magodo** [comment]
@yukihonhk Would you please provide more details about to reproduce this issue and the error message?

**Comment by magodo** [comment]
@yukihonhk I'm gonna close this issue for now as I didn't hear from you for a while. Please feel free to reopen it if you are still facing this issue.
