### ISSUE TITLE
aztfy skips storage accounts

### ISSUE THREAD

**Issue by andyghc** [Azure/aztfy#156]
When running aztfy on a resource group that only has a storage account, the aztfy command skips over the storage account.  No reason given for why it's being skipped, it just lists all the resources and lists (Skip) with each of them.  

` Azure Terrafy

     EQ_Azure_RG_Mgmt01_CostMgt

    7 items

  │ /subscriptions/xxx-yyy-zzz/resourceGroups/Test_RG/providers/Microsoft.Storage/storageAccounts/myteststoracc538asd
  │ (Skip)

    /subscriptions/xxx-yyy-zzz/resourceGroups/Test_RG/providers/Microsoft.Storage/storageAccounts/myteststoracc538asd/blobServices/de
    (Skip)

    /subscriptions/xxx-yyy-zzz/resourceGroups/Test_RG/providers/Microsoft.Storage/storageAccounts/myteststoracc538asd/fileServices/de
    (Skip)

    /subscriptions/xxx-yyy-zzz/resourceGroups/Test_RG/providers/Microsoft.Storage/storageAccounts/myteststoracc538asd/queueServices/d
    (Skip)

    /subscriptions/xxx-yyy-zzz/resourceGroups/Test_RG/providers/Microsoft.Storage/storageAccounts/myteststoracc538asd/tableServices/d
    (Skip)

    /subscriptions/xxx-yyy-zzz/resourceGroups/Test_RG/providers/Microsoft.Storage/storageAccounts/myteststoracc538asd/blobServices/de
    (Skip)

    💡/subscriptions/xxx-yyy-zzz/resourceGroups/Test_RG
    azurerm_resource_group.res-6
`

**Comment by magodo** [comment]
These are embedded service that are created together with the storage account. There is no correspondance in TF.

**Comment by AlexLudwigITDienstleistungen** [comment]
The same problem exists here. You can add the resource manually by specifying the name like azurerm_storage_account.StoAccName.
The problem also occurs with Key Vaults, Windows virtual machines and virtual machine extensions.
After manually declaring the names, the import runs correctly except for storage accounts that use Azure AD authentication.
Import for storage containers also fails with the following error message:

`/subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/VeeamVBO-dev/providers/Microsoft.Storage/storageAccounts/veeamvbodev/blobServices/default/containers/vbodata`
`exit status 1`
`Error: Cannot import non-existent remote object`
`While attempting to import an existing object to`
`"azurerm_storage_container.vbodata", the provider detected that no object`
`exists with the given id. Only pre-existing objects can be imported; check`
`that the id is correct and that it is associated with the provider's`
`configured region or endpoint, or use "terraform apply" to create a new`
`remote object for this resource.`

@magodo As you can see, there is definitely an equivalent in terraform. This is the reason why I am totally confused why these objects are not recognized correctly.

**Comment by magodo** [comment]
So you are trying to import the container rather than the storage account (as the ids in your issue description is truncated, I thought you were trying to import things like `/subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/VeeamVBO-dev/providers/Microsoft.Storage/storageAccounts/veeamvbodev/blobServices/default`).

**Comment by andyghc** [comment]
Sorry yes, the output above was truncated.  But there is nothing special going on here.  I am running aztfy on a resource group with only one resource in it which is a storage account.  Surely a storage account can be imported with aztfy right?  I've seen it import much more complicated things like Application Gateway WAF's etc, but why skip a storage account?  

Is there some sort of trick I need to run to import storage accounts?  

Attached is the output of a simple aztfy command "aztfy <resource_group_name>" in an empty directory.  

I'm using aztfy version:   v0.5.0(f957fc1)

![Screenshot 2022-06-25 112800](https://user-images.githubusercontent.com/18387182/175753123-a918623f-80d9-4400-8f67-613d1c3e2b74.png)

**Comment by magodo** [comment]
From the README:

> In interactive mode, aztfy list all the resources resides in the specified resource group. For each resource, **user is expected to input the Terraform resource address in form of <resource type>.<resource name> (e.g. azurerm_linux_virtual_machine.test)**. Users can press r to see the possible resource type(s) for the selected import item (though this is not guaranteed to be 100% accurate). In case there is exactly one resource type match for the import item, that resource type will be automatically filled in the text input for the users, with a bulb line prefix as an indication.

The reason why it is showning `skip` is because `aztfy` isn't smart enough to know that resource corresponds to a storage account. You have to specify it yourselves. But we have some work going on to improve this.

**Comment by sosoriov** [comment]
@magodo  I agree but at least it should generate the storage account definition in TF which is not happening in my case. It only generates the RG. I'm running v0.5.0

**Comment by sosoriov** [comment]
that did the trick. Thanks @magodo !

**Comment by magodo** [comment]
This issue is fixed in the v0.6.0.
