### ISSUE TITLE
aztfy command not found after install | MacOS 12.4

### ISSUE THREAD

**Issue by zveroboy152** [Azure/aztfy#159]
After installing go with `brew install go` and then installing aztfy with `go install github.com/Azure/aztfy@latest` I cannot run aztfy.

It looks like nothing loaded into my environment:

`➜  ~ which aztfy`
`aztfy not found`

**Comment by magodo** [comment]
Presumably you should `export PATH=$PATH:$GOPATH/bin` as that is where `go install` installs executables into.

**Comment by koudaiii** [comment]
If you do not need the **latest** version, aztfy(**0.5.0** [Release version](https://github.com/Azure/aztfy/releases)) is now supported by homebrew https://github.com/Homebrew/homebrew-core/pull/104342 .

https://github.com/Azure/aztfy/tree/4945cfbc82d9b52be5a2f8d312575b325e46de99#from-homebrew

**Comment by zveroboy152** [comment]
> 

Perfect, I installed it via brew and we're all good now.  Thanks!
