### ISSUE TITLE
Ability to import entire subscription

### ISSUE THREAD

**Issue by cedrox** [Azure/aztfy#16]
Would be interesting to get full subscription as terraform project in one shot

**Comment by MohnJadden** [comment]
Not to be contrarian but if we're looking to import 500 resource groups within one subscription, it really doesn't matter how aztfy translates from ARM to Terraform.  Without the ability to cover subscription scopes, the onus falls on us to find a way to loop through RGs individually until issue #28 is completed.  

As a workaround idea, is there some way to have aztfy check within the subscription scope that a user has already set via `az account set --subscription %subscriptionNameGoesHere%` to query all available RGs, then run them through the interface or non-interactive mode as it already does?

**Comment by magodo** [comment]
@MohnJadden That is possible, however, one major problem of that is that we are importing the rg one by one, which means the ARM template is still in scope of one RG. This results into the combined ARM templates will miss the cross RG dependencies.
