### ISSUE TITLE
Possibly ignore Azure queries in Log Analytics Workspaces

### ISSUE THREAD

**Issue by shaneholder** [Azure/aztfy#163]
When importing a RG with a log analytics workspace there are several queries that are being imported which seem to be provided by Azure and not custom queries that were created.  They should probably be excluded from an import.

resource "azurerm_log_analytics_saved_search" "res-141" {
  category                   = "Security Info Notable Issues"
  display_name               = "Computers with failed sudo logons"
  log_analytics_workspace_id = "/subscriptions/<SUB>/resourceGroups/<RG>/providers/Microsoft.OperationalInsights/workspaces/<WORKSPACE>"
  name                       = "Security(<WORKSPACE>)_SecurityInfoNotableIssues|ComputersWithFailedSudoLogons"
  query                      = "Syslog | where (Facility == 'authpriv' and SyslogMessage has 'sudo:auth' and (SyslogMessage has 'authentication failure' or SyslogMessage has 'conversation failed')) or ((Facility == 'auth' or Facility == 'authpriv') and SyslogMessage has 'user NOT in sudoers') | summarize count() by Computer"
  depends_on = [
    azurerm_log_analytics_workspace.res-13,
  ]
}

**Comment by magodo** [comment]
@shaneholder Unfortunately, currently `aztfy` is not smart enough to differentiate Azure defined queries and user defined queries. While you can mark these identified queries to be skipped in the resource list by selecting them and typing the <kbd>del</kbd>. Or you can do a `terraform state rm <addr>` post running `aztfy` to remove them manually.

**Comment by magodo** [comment]
@shaneholder I'm gonna close issue for now. Please feel free to reopen it if you have any question.
