### ISSUE TITLE
Azure Government Use

### ISSUE THREAD

**Issue by TaraECI** [Azure/aztfy#168]
Hello - 
I love this tool but if I try to run it Azure Gov it errors out because
https://management.azure.com needs to be https://management.usgovcloudapi.net/ 
when exporting the templates (POST https://management.azure.com/subscriptions/subscriptionID/resourcegroups/RG-Name/exportTemplate)

I know this may well be by design but please imagine what it's like to be dumped with undefined infra in GovCloud you need to get into TF fast.

Don't suppose there is anyway around this?

**Comment by magodo** [comment]
@TaraECI You can specify environment variable `ARM_ENVIRONMENT` to `usgovernment`, then it should target towards the right endpoint.

**Comment by skorb-ucb** [comment]
Seeing the same thing here, but set ARM_ENVIRONMENT=usgovernment doesn't seem to have any effect.  A basic aztfy command still errors out with an authentication failure message and we still see requests attempting to get out to management.azure.com in the firewall logs.

**Comment by TaraECI** [comment]
Would it be possible to get a compiled build of this to test for Windows AMD64 head of the release?

**Comment by skorb-ucb** [comment]
FWIW I tried cloning the repo this week but after building we still seem to have authentication issues. Azure CLI login works fine, ARM_ENVRIONMENT is set to 'usgovernment', and terraform init/plan run without error, but aztfy still throws the following:

![image](https://user-images.githubusercontent.com/94199515/178800689-d66e22bb-9457-4f5e-8559-c55085db798f.png)

Not sure why it seems to be failing on querying IMDS.  This is an Azure instance and IMDS is running and can be queried.

**Comment by magodo** [comment]
@skorb-ucb This should've been fixed in https://github.com/Azure/aztfy/pull/171, can you please have another try?

**Comment by TaraECI** [comment]
@magodo @skorb-ucb I have bit the bullet, installed go and cloned the main branch and can confirm that I can successfully import and generate Terraform configs  - thank you both.

**Comment by skorb-ucb** [comment]
@magodo, I must have just cloned before that change was committed.  Pulled the latest, compiled, and it's working!

**Comment by atwork317** [comment]
This still does not work for Azure Government.

**Comment by magodo** [comment]
@atwork317 I've just verified the latest releas (v0.9.0) works fine for US Gov cloud.

**Comment by atwork317** [comment]
@magodo Thank you for checking. I'm going to try it out now. I'll update with results today.
