### ISSUE TITLE
Question about aztfy

### ISSUE THREAD

**Issue by elvovsky** [Azure/aztfy#170]
I was trying to use aztfy, however after it enumerated the resources, and running import, it says that import fails. 
How do I go about troubleshooting what is going on? Is there a way to generate a log (debug) . Any help/advice is appreciated

**Comment by magodo** [comment]
In interactive mode, if there is an error during importing, users will be routed back to the resource list view, where the erronous item will be prefixed by a ❌. Select that item and press <kbd>e</kbd>, it will show the detailed error message.

**Comment by elvovsky** [comment]
I don't get "X" , I get "!" . It seems that the only green one is assigned identity . However when I do press "e", I do see the error message, which basically tells me no object exists with this id. I do know that it exists . I guess I can't get much further with it at this point

**Comment by magodo** [comment]
@elvovsky  Could you please provide the error message here?
