### ISSUE TITLE
aztfy skipping AKS cluster

### ISSUE THREAD

**Issue by niven01** [Azure/aztfy#174]
When running aztfy again my resource group containing my AKS cluster it skips the cluster but gathers config for Resource Group and Node pool. Can aztfy currently grab AKS cluster config?

```
 Azure Terrafy

   MY-AKS-RESOURCE-GROUP

  3 items

│ /subscriptions/1234-abcd-5678-efgh-xxxxxx/resourceGroups/MY-AKS-RESOURCE-GROUP/providers/Microsoft.ContainerService/managedClusters/MY-AKS-CLUSTER-01
│ (Skip)
  
💡/subscriptions/1234-abcd-5678-efgh-xxxxxx/resourceGroups/MY-AKS-RESOURCE-GROUP/providers/Microsoft.ContainerService/managedClusters/MY-AKS-CLUSTER-01/agentPools/nodepool01
 azurerm_kubernetes_cluster_node_pool.res-1

💡/subscriptions/1234-abcd-5678-efgh-xxxxxx/resourceGroups/MY-AKS-RESOURCE-GROUP
 azurerm_resource_group.res-2
```

I am running `aztfy version v0.5.0(f957fc1)`

**Comment by niven01** [comment]
Looking at this further my understanding is that aztfy for whatever reason cannot automatically recognise this as a `azurerm_kubernetes_cluster` resource. If I manually specify as below the config is generated. Is this expected with the current release of aztfy?


```
 Azure Terrafy

   MY-AKS-RESOURCE-GROUP

  3 items

│ /subscriptions/1234-abcd-5678-efgh-xxxxxx/resourceGroups/MY-AKS-RESOURCE-GROUP/providers/Microsoft.ContainerService/managedClusters/MY-AKS-CLUSTER-01
│ > azurerm_kubernetes_cluster.res-3

```

**Comment by magodo** [comment]
@niven01 Yes! In the future, the resource type auto detection will be improved, and the AKS cluster should be resolved automatically.
