### ISSUE TITLE
Could the Delete action be toggled in interactive mode?

### ISSUE THREAD

**Issue by MohnJadden** [Azure/aztfy#184]
When working in interactive mode, if we delete a resource, it stays in Skip state and there's no way to undo it other than quitting and re-running aztfy.  Is there any way to have the Delete key toggle between Skip and normal?

**Comment by magodo** [comment]
@MohnJadden You can press enter and specify the resource address manually. If you are not sure about the correct resource type, just press <kbd>ESC</kbd> to quit the input mode and press <kbd>r</kbd> to let `aztfy` tell you the recommended resource type.

**Comment by magodo** [comment]
@MohnJadden As we haven't heard from you for a long while, I'm going to close this issue for now. Please feel free to reopen it you still have any question.
