### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by pir8g33k** [Azure/aztfy#190]
i encountered some issue in windows powershell even we set  Set-AzContext for the subscription to use and but the aztfy cant locate the right resource, and the result we have multiple subscription.

 
Error: retrieving Virtual Machine "VM!" (Resource Group "rg_groupname"): compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: 
autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'rg_groupname' could not be found."

**Comment by magodo** [comment]
@pir8g33k Currently, the AzureRM provider doesn't support Powershell auth, it only supports Azure CLI auth and the others, please check https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#authenticating-to-azure for details.

**Comment by pir8g33k** [comment]
I see understood, ok let me try on my Linux or Mac, thanks for the info

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
