### ISSUE TITLE
Resources never written to a file.

### ISSUE THREAD

**Issue by bourbonfgiles** [Azure/aztfy#191]
Hello,

I'm using Aztfy to target an Azure resource group and write the Terraform. I successfully point Aztfy to an authenticated resource group, and Aztfy successfully creates mappings from Azure resources into Terraform objects. When I press "W" to write this out, Terraform state is populated but I don't get a main.tf or similar with the Terraform code.

Can somebody point out what step I am missing to get the Terraform code?

Thanks.

**Comment by magodo** [comment]
What CLI argument you have specified? If you run it via `--append`, from the README, it says:

> Especially, the file generated by aztfy in this case will be named differently than normal, where each file will has .aztfy suffix before the extension (e.g. main.aztfy.tf), to avoid potential file name conflicts. If you run aztfy --append multiple times, the generated config in main.aztfy.tf will be appended in each run.

**Comment by bourbonfgiles** [comment]
> What CLI argument you have specified? If you run it via `--append`, from the README, it says:
> 
> > Especially, the file generated by aztfy in this case will be named differently than normal, where each file will has .aztfy suffix before the extension (e.g. main.aztfy.tf), to avoid potential file name conflicts. If you run aztfy --append multiple times, the generated config in main.aztfy.tf will be appended in each run.

My fault, it wasn't outputting content as there were errors in the import step, resolved.
