### ISSUE TITLE
Not pulling all the configs.

### ISSUE THREAD

**Issue by EttienneScheepers** [Azure/aztfy#196]
Hi Guys

I pulled the config from my environment but I see that the main components that I am looking to get the code for are getting skipped.
I see VMs and storage are skipped is this a bug or is it working as expected?

Regards
Ettienne

**Comment by magodo** [comment]
@EttienneScheepers Have you tried with the latest release (v0.6.0), where it should be smart enough to deduce those resource types by their ids for you?

**Comment by EttienneScheepers** [comment]
@magodo Yes, I set up Terrafy yesterday from scratch with the latest build it shows that it skipped it but not sure why.

**Comment by magodo** [comment]
@EttienneScheepers Could you please elaborate more about how you run the tool? Do you run it via `aztfy rg <rgname>`? If so, could you please show me the screen that those main resources are marked as "Skipped"?

**Comment by EttienneScheepers** [comment]
@magodo  Yes, I run it via aztfy rg. Here is a screenshot of the files that it skipped. I had a chat with one of my colleagues and he advised he tried to use aztfy in the past and experienced the same issue and never used it again due to this issue.

![image](https://user-images.githubusercontent.com/74060734/183048901-f9e501ad-c484-4802-94bd-9a9e7283216a.png)

**Comment by magodo** [comment]
@EttienneScheepers It appears the version you used is prior to v0.6.0. Would you please double check the version?

Meanwhile, could you please run `aztfy` with `AZTFY_LOG_PATH` set to a path for logging, and paste the link to the log here (with sensitive info redacted) so that I can further investigate the issue?

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
