### ISSUE TITLE
Ability to export a comprehensive HCL

### ISSUE THREAD

**Issue by magodo** [Azure/aztfy#207]
`aztfy` imports resources into terraform state, then use [`tfadd`](https://github.com/magodo/tfadd) under the hood to convert the HCL from the state. As is stated in the `tfadd`'s README, currently `tfadd` supports a *full* mode and a *partial* mode:

> - In full mode, tfadd outputs all non-computed properties in the generated config. The generated config might be invalid for kinds of reasons, where manual modification is needed. But the benefit is that it works for any Terraform provider.
> - In partial mode, tfadd only outputs properties without Optional+Computed properties, with cross property constraints taken into consideration. This mode aims aims to generate a valid Terraform config. 

`aztfy` is now always using the `partial` mode as it aims to generate a valid configuration, to better meets its goal to manage resource under terraform. Whilst we are getting feedbacks from users that the `full` mode sometimes are also valuable. E.g. users want to inspect the full properties of the resource in its HCL form, they may further manually modify the full HCL code to make it as a template for further customization.

Propose to introduce an global option that applies to both single resource mode and resource group mode, to allow users to choose between the `full`/`partial` export mode.

**Comment by grayzu** [comment]
@magodo @stemaMSFT  We should find another name for this parameter as this would make me wonder "Why would I not want to export the full config"? --all-properties maybe? --full-mode to align with tfadd maybe?

**Comment by magodo** [comment]
@grayzu That makes sense, I prefer `--all-properties`/`--full-properties`.

**Comment by stemaMSFT** [comment]
--full-properties with a short form of -fp sounds good to me :)
