### ISSUE TITLE
Customizable query to list resources

### ISSUE THREAD

**Issue by magodo** [Azure/aztfy#208]
Currently, `aztfy` only works for either resource group mode or single resource mode. In the resource group mode, users can either select the resources to be "terrafied" by UI or by feeding a mapping file. The mapping file is good enough to be used within a resource group, however, some users want more customized scopes to be imported (e.g. by `tags`).

In order to support that, we can consider integrating azure resource graph (a.k.a ARG)to `aztfy`, which introduces a 3rd mode: "query mode". In this mode, ARG is used only for listing resource ids by user's customized query. Then `aztfy` "terrafies" these selected resources. Note that one caveate of this comparing to the resource group mode is that it no longer benefit from ARM template, which means the cross resource dependencies are missing.

**Comment by stemaMSFT** [comment]
Though we may not need it immediately, adding a filtering option to the command using ARG querying on resource types would be useful for `-rg --resource-group` mode. Along the lines of `--filter -f` that would take resource types as input.
