### ISSUE TITLE
Unable to import azure ssh key

### ISSUE THREAD

**Issue by archangel2018** [Azure/aztfy#211]
**Version**: aztfy version v0.6.0(18b614b)
**OS**: Ubuntu 20.04.4 LTS

**Error:**
/subscriptions/fd652643-255c-4dd5-acc0-52f188912fe2/resourceGroups/rg-bl-inf-msdn-cus/providers/Microsoft.Compute/SshPublicKeys/ssh-bl-pentest-msdn-cus
exit status 1
Error: parsing Resource ID "/subscriptions/fd652643-255c-4dd5-acc0-52f188912fe2/resourceGroups/rg-bl-inf-msdn-cus/providers/Microsoft.Compute/SshPublicKeys/ssh-bl-pentest-msdn-cus": parsing
"/subscriptions/fd652643-255c-4dd5-acc0-52f188912fe2/resourceGroups/rg-bl-inf-msdn-cus/providers/Microsoft.Compute/SshPublicKeys/ssh-bl-pentest-msdn-cus": parsing segment "staticSshPublicKeys": expected the segment "SshPublicKeys"
  to be "sshPublicKeys"

Besides, Only the statefile is created. the main.tf resource file is not created if any error is present during the import process.

**Comment by magodo** [comment]
@archangel2018 Thank you for submitting this! The issue has already been fixed in #179. In order to generate the tf code on error, please also specify `--continue/-k` in batch mode, or mark the error resource as skipped in interactive mode.
