### ISSUE TITLE
issue when using -backend-type

### ISSUE THREAD

**Issue by MHSF-HiteshM** [Azure/aztfy#213]
running the below but getting error saying flag provided but not defined: -backend-type

aztfy --backend-type=azurerm --backend-config=resource_group_name=tfstate --backend-config=storage_account_name=tfstatetest --backend-config=container_name=tfstate --backend-config=key=terraform.tfstate test-vm02

**Comment by magodo** [comment]
@MHSF-HiteshM You'll need to specify either `resource-group` or `resource` subcommand right after `aztfy`, then you can add on the options afterwards.

**Comment by MHSF-HiteshM** [comment]
Thanks for your reply when I do this I get an error saying more than one resource groups specified 

aztfy rg test-vm02 --backend-type=azurerm --backend-config=resource_group_name=tfstate --backend-config=storage_account_name=tfstatetest --backend-config=container_name=tfstate --backend-config=key=terraform.tfstate

**Comment by magodo** [comment]
@MHSF-HiteshM You'll then need to specify your rg name after the options:

```
USAGE:
   aztfy resource-group [option] <resource group name>
```

**Comment by MHSF-HiteshM** [comment]
Sorry I should of been more clear. I am specifying the resource group. 'test-vm02' is the name of the resource group in azure  but I still get an error saying more than one resource groups specified 

aztfy resource-group test-vm02 --backend-type=azurerm --backend-config=resource_group_name=tfstate --backend-config=storage_account_name=tfstate01092022 --backend-config=container_name=tfstate --backend-config=key=terraform.tfstate test-vm02

**Comment by magodo** [comment]
@MHSF-HiteshM I mean you shall run like this:

`aztfy resource-group --backend-type=azurerm --backend-config=resource_group_name=tfstate --backend-config=storage_account_name=tfstatetest --backend-config=container_name=tfstate --backend-config=key=terraform.tfstate test-vm02`

**Comment by MHSF-HiteshM** [comment]
This works! thanks
