### ISSUE TITLE
Error: Parsing resource ID

### ISSUE THREAD

**Issue by dburt669** [Azure/aztfy#221]
What: I performed an aztfy rg rg-name
resource group contained an sshPublicKeys resource
Got:
Error Message: expected the segment "SshPublicKeys" to be "sshPublicKeys"
![2022-09-13_8-20-21-parseError](https://user-images.githubusercontent.com/59170183/189906989-39e0195b-ae0a-4853-a53a-f2f9885c65c5.png)

all other resources were parsed successfully, however 

overall operation failed.

**Comment by magodo** [comment]
@dburt669 This duplicates to #211, which fixed in #179.
