### ISSUE TITLE
Error: expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP

### ISSUE THREAD

**Issue by soysoliscarlos** [Azure/aztfy#226]
After Apply `aztfy.exe rg rg-vm`

if I try to do a Terraform plan a receive the following error for the azurerm_network_security_rule

```
│ Error: expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP
│
│   with azurerm_network_security_rule.res-4,
│   on main.tf line 32, in resource "azurerm_network_security_rule" "res-4":
│   32:   protocol                    = "TCP"
```
Of course, I just edit the file, and that's it.

It will be interesting if when I import my terraform configuration, the TCP protocol will be import as "Tcp"

**Comment by magodo** [comment]
@soysoliscarlos Thank you for submitting this! There is another issue #72 tracking this problem. In order to avoid duplication, would you please subscribe #72 for any progress?

Thank you!
