### ISSUE TITLE
request to work in gov cloud

### ISSUE THREAD

**Issue by mcarter106** [Azure/aztfy#228]
This worked great in my commercial account but when I tried to use it in Azure Gov cloud it could not see my sub.  Any way to update this so that it works on Gov cloud too?

**Comment by magodo** [comment]
@mcarter106 `aztfy` could work on Gov cloud if you set environment variable `ARM_ENVIRONMENT=usgovernment`.

**Comment by mcarter106** [comment]
Thank you.  Great news!

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
