### ISSUE TITLE
Issue with importing blobs / containers

### ISSUE THREAD

**Issue by DanG-arch** [Azure/aztfy#229]
I get this following error when I try to provide the https:// url for the container

Error: invalid resource id: id should start with "/"

When I try to import as part of  resource group import, I get this error:

Failed to import https://xxxxyyyyyyy.blob.core.windows.net/%5Cazure-webjobs-secrets as azurerm_storage_container.res-35: exit status 1

Error: retrieving Container "\\azure-webjobs-secrets" (Account "xxxxyyyyyyy" / Resource Group "rg-xxxxxxx"): containers.Client#GetProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidUri" Message="The requested URI does not represent any resource on the server.\nRequestId:2993a3c4-101e-00a8-3d2f-cd69dd000000\nTime:2022-09-20T20:31:14.7346835Z"

**Comment by magodo** [comment]
@DanG-arch Thank you for submitting this! In this case, per [aztft](https://github.com/magodo/aztft#pesudo-resource-id) you shall use the pesudo Azure management plane resource id: `/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/account1/blobServices/default/containers/container1/blobs/blob1`

**Comment by magodo** [comment]
Do you mean the resource ID used in AzureRM provider? If yes, then it won't be changed. What `aztfy` does is it will under the hood leverage `aztft` to map the **azure resource id** to **terraform resource id**. For the container blob case, since it is a data plane only resource, which means it has no **azure resource id**, that's why we define a pesudo resouce id in `aztft` for it. Then `aztft` convert that pesudo id to its **terraform resource id**, i.e. the HTTP url form, so that the provider can consume it.

**Comment by magodo** [comment]
Sorry that I thought you were trying to import a container blob, while actually your error indicates that you were importing a container in rg mode. So in this case, the error is from the provider during the importing. Would you please try to manually import that resource (using the above URL) via `terraform import azurerm_storage_container.test https://xxxxyyyyyyy.blob.core.windows.net/%5Cazure-webjobs-secrets`?

**Comment by magodo** [comment]
Could you try run `aztft -api -import <container's management resource id>` to see what it returns? Meanwhile, could you try to look into the ARM template of that resource group to see how the container id looks like?

BTW, I've verified it works fine for me when terrafying a rg with storage container within it.

**Comment by magodo** [comment]
@DanG-arch Thanks! From the prompt, it is on Windows. I realized that's a bug in aztft, where it uses `filepath.Join` for constructing the resource id.

**Comment by magodo** [comment]
@DanG-arch I'm working on this now, a PR will be submitted soon. Bear with me :)

**Comment by magodo** [comment]
@DanG-arch PR #230 is merged, which should fix this issue on Windows. Please try out with the main branch.
