### ISSUE TITLE
Add to Winget

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [Azure/aztfy#239]
Would be a very useful tool if getting rapid releases to upload to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by andrew-flatters-bliss** [comment]
Done the work involved in this - seems you guys added MSI last release which made this easier https://github.com/microsoft/winget-pkgs/pull/81043

**Comment by andrew-flatters-bliss** [comment]
I added this as a tag so it should pick it up - doesn't look like its been approved yet on the other end - can always reopen this ticket until that has done and do a PR to make the readme changes?

**Comment by magodo** [comment]
@andrew-flatters-bliss Yes, let's keep this issue open for now. Still, thank you for your effort!

**Comment by andrew-flatters-bliss** [comment]
No problem, the team at winget have done a really nice job adding new packages in all honesty - even spins up a Windows Sandbox to test them in which is loverly.

**Comment by andrew-flatters-bliss** [comment]
Looks like that PR has been merged final command been `winget install Microsoft.AzureAztfy`

**Comment by magodo** [comment]
@andrew-flatters-bliss It works! Whilst, do you think it is feasible to rename the package identifier to `aztfy`, so to be consistent across all package managers?

**Comment by magodo** [comment]
@andrew-flatters-bliss Good to know that, thank you! I'll add it to the README then.

**Comment by andrew-flatters-bliss** [comment]
@magodo on the latest version update looks like the package maintainers suggested in the PR a solution so should now able to do `winget install aztfy`

**Comment by magodo** [comment]
@andrew-flatters-bliss Cool, thanks!
