### ISSUE TITLE
[Feature Request] Show diff / changes of resources against existing state file

### ISSUE THREAD

**Issue by DanG-arch** [Azure/aztfy#248]
Would love to have a feature where I can provide an existing state file (and the aztfy mapping file) and then get a HCL output of differences between existing local state file and remote azure resources.

Ex: 

aztfy -show-azure-changes -state-file .1.tfstate

**Comment by magodo** [comment]
Isn't that already achieved by `terraform plan`?

**Comment by magodo** [comment]
You don't have to append tf code into main.tf, but can be other file names as long as it resides in the same directory as main. `--append` does what you want.

**Comment by magodo** [comment]
@DanG-arch Since we haven't get further response from you, I'll mark this issue as closed for now. Feel free to reopen it if the issue still remains.
