### ISSUE TITLE
Allow Revert Skip

### ISSUE THREAD

**Issue by cjoecker** [Azure/aztfy#265]
I'm not sure if I'm overseeing something but is there a way to revert a skipped resource in interactive mode?

After going through a long list, is easy to press `delete` by mistake and want to revert it.
I just see these options:
![image](https://user-images.githubusercontent.com/46030630/196669809-fe9c1120-f905-42be-9634-800549932817.png)

**Comment by magodo** [comment]
@cjoecker You can press `r` to get the recommended resource type, then type it together with its name.

**Comment by cjoecker** [comment]
@magodo that's a nice feature but is not what I intend to do.

What I intend to do is to unskip a resource once I selected to skip it.
My expectation would be, that once I press `delete`, the resource is `(Skip)`. If I press it again for the same resource, it shows the old value again. That is not happening right now.

**Comment by dbhaigh** [comment]
I'm certainly in favour of this enhancement - otherwise you are back to square one and re-running the initial import again
