### ISSUE TITLE
Ability to import multiple resource groups

### ISSUE THREAD

**Issue by magodo** [Azure/aztfy#28]
Adding ability to import multiple resource groups rather than only one.

Currently, we leverage ARM template to list resources inside a resource group and get the inter-resource dependencies. Unfortunately, ARM template only provide dependencies within one resource group, but isn't smart enough to get cross resource group dependencies. This means the generated TF config might has incomplete resource dependencies.

E.g. Using `aztfy` to import infra provisioned by below cfg, the resulted NIC will only have dependency on `azurerm_resource_group.test2`, but not on the subnet.

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-mgd1"
  location = "westus"
}

resource "azurerm_resource_group" "test2" {
  name     = "acctestRG-mgd2"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvn-321"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "test" {
  name                = "acctestni-321"
  location            = azurerm_resource_group.test2.location
  resource_group_name = azurerm_resource_group.test2.name

  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.test.id
    private_ip_address_allocation = "Dynamic"
  }
}
```

**Comment by richeney** [comment]
Short term, here is a Bash workaround for this.

Assumes that you have used aztfy on two resource groups (e.g. rg1 and rg2). Also all Terraform identifiers (i.e. output from `terraform state list`) are unique across the state files, and `terraform validate` is OK on each config.

```bash
mkdir union
cp -pr rg1/.terraform* rg1/provider.tf union
sed 's/^}$/}\n/g' rg1/main.tf rg2/main.tf > union/main.tf
jq -s '(.[0]|del(.resources)) + {resources: (.[0].resources + .[1].resources)}' rg1/terraform.tfstate rg2/terraform.tfstate > union/terraform.tfstate
```

The sed command is only needed to add a new line after each left-aligned block. Ideally it would be `cat rg1/main.tf rg2/main.tf > union/main.tf` but that currently errors due to the file format.

The jq expression slurps in both files, takes all keys except resources from the first and then adds the resource key back in after concatenating the two resource arrays. 

Quick and dirty, but it *should* work.

**Comment by MohnJadden** [comment]
This feature would be EXTREMELY handy for me at the moment - I'm dealing with a tfstate that's unusable and need to re-build it by importing.  Having aztfy in existence helps, but I'll have to figure out how to merge the output of several resource groups back into one state managed by one main.tf file.
@richeney 's solution is great for bash environments but I'm using regular old Windows and VS Code, so adding "learn bash" on top of "return Terraform to working" is a bit of a roadblock.  Even without my emergency state we should definitely be able to natively have a bunch of RGs go into one state.  

Having aztfy do the same thing it does for individual (and hopefully in the future, groups of) RGs at a subscription level would be even better.  If there's not an issue for that already I'll be opening one.

**Comment by richeney** [comment]
@MohnJadden As a short-term workaround there isn't anything stopping the same JSON merge being done using PowerShell cmdlets. If anything, it should be easier and cleaner than Bash, as PowerShell handles objects rather well. 

I'll see if I can work out an equivalent.

**Comment by MohnJadden** [comment]
There's also the consideration that not everyone running an Azure environment is a Powershell deity, but I also didn't realize yesterday that VS Code has a Bash terminal :-)  I'll be taking a shot at your original workaround with gratitude and appreciation!

**Comment by magodo** [comment]
@MohnJadden To import multiple RGs, you can now run:

```shell
aztfy rg --append --name-pattern "rg1-*" rg1
aztfy rg --append --name-pattern "rg2-*" rg2
...
```

**Comment by richeney** [comment]
Fantastic @magodo. The new [v0.6](https://github.com/Azure/aztfy/releases/tag/v0.6.0) functionality looks great!
