### ISSUE TITLE
Somehow

### ISSUE THREAD

**Issue by John-Donalson** [Azure/aztfy#287]
Somehow last week  i was able to use aztfy rg <name> fine. now this week, every resource i try gives "Error: More than one resource groups specified" the only thing that changed was i now have 4 multiple subscriptions, but did set-azcontext.... so confused

**Comment by magodo** [comment]
@John-Donalson That is because the command you used to invoke `aztfy` is incorrect, please chekcout `aztfy rg -h`.

@m1rl0k Please open another issue for a new problem. For your specific case, it duplicates to #257.
