### ISSUE TITLE
Aztfy pipeline

### ISSUE THREAD

**Issue by aminniktash2010** [Azure/aztfy#310]
We are writing a .yaml pipeline automating the terrafy workflow, as we need to automate this based on load of resource we need to import, using Azurerm provider and targeting blob storage for backend for aztfy, however not sure how we can change the path from pipeline agent system directory to another path or publish the imported data on? at the moment we are getting below error:

Error: the output directory "/home/vsts/work/1/s" is not empty

So we need to get aztfy path optional.

Thanks

**Comment by magodo** [comment]
@aminniktash2010 The error indicates the output directory of `aztfy`, which by default is the current working directory of your pipeline, is not empty. In your case, you might want to create an empty temporary directory, then let `aztfy` to use it:

```
outdir=$(mktemp -d)
aztfy <cmd> -o $outdir [other options]
```

**Comment by aminniktash2010** [comment]
Thanks @magodo  As it would work for sure however Not sure if I miss an argument?

Error: flag provided but not defined: -o

- bash: aztfy -o $outdir rg --backend-type=azurerm --backend-config=resource_group_name=????? --backend-config=storage_account_name=???? --backend-config=container_name=??????? --backend-config=key=terrafy/terraform.tfstate  --non-interactive My resource

and If I add  <cmd>  getting error
 cmd: No such file or directory

My pipeline agent is Ubuntu 

Thanks again

**Comment by magodo** [comment]
If you are importing a resource group, you'll do:

```shell
aztfy rg -o $outdir --backend-type=azurerm --backend-config=resource_group_name=????? --backend-config=storage_account_name=???? --backend-config=container_name=??????? --backend-config=key=terrafy/terraform.tfstate --non-interactive <rg-name>
```

**Comment by aminniktash2010** [comment]
> If you are importing a resource group, you'll do:
> 
> ```shell
> aztfy rg -o $outdir --backend-type=azurerm --backend-config=resource_group_name=????? --backend-config=storage_account_name=???? --backend-config=container_name=??????? --backend-config=key=terrafy/terraform.tfstate --non-interactive <rg-name>
> ```

**Comment by magodo** [comment]
@aminniktash2010 I'm gonna close this issue for now. Please feel free to reopen it if the issue still remains.
