### ISSUE TITLE
Error: retrieving Database (PostgresSQL)  Status=400

### ISSUE THREAD

**Issue by dermoritz** [Azure/aztfy#311]
I am just installed the current (0.9.0) aztfy on my windows machine.
I tried to terrafy a resource group of my subscription.

After starting it with resource-group command. While most resources ("245 items") went fine i got an error for 3 of them (the last 3 items for DB resource):

```
  │ ❗️/subscriptions/xyz/resourceGroups/cc-resource-group/providers/Microsoft.DBforPos
  │ azurerm_postgresql_flexible_server_database.res-234

    ❗️/subscriptions/xyz/resourceGroups/cc-resource-group/providers/Microsoft.DBforPos
    azurerm_postgresql_flexible_server_database.res-235

    ❗️/subscriptions/xyz/resourceGroups/cc-resource-group/providers/Microsoft.DBforPos
    azurerm_postgresql_flexible_server_database.res-236
```

The error is:

```
  /subscriptions/xyz/resourceGroups/cc-resource-group/providers/Microsoft.DBforPostgreS

  exit status 1

  Error: retrieving Database (Subscription: "xyz"
  Resource Group Name: "cc-resource-group"
  Server Name: "cc-db"
  Database Name: "azure_maintenance"): databases.DatabasesClient#Get: Failure responding to request: StatusCode=400 --
  Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameterValue" Message="Invalid
  value given for parameter databaseName. Specify a valid parameter value.
```

other items for this resource went fine:

```
  │ ✅/subscriptions/1e8a445d-7e71-4de6-a8d9-a554e9e99007/resourceGroups/cc-resource-group/providers/Microsoft.DBforPost
  │ azurerm_postgresql_flexible_server_configuration.res-233
```

side note, one vnet was skiped:

```
 /subscriptions/1e8a445d-7e71-4de6-a8d9-a554e9e99007/resourceGroups/cc-resource-group/providers/Microsoft.Network/pri
    (Skip)
```

Any ideas what is the cause of the error?

**Comment by magodo** [comment]
@dermoritz Those 3 failed ones (named `azure_maintenance`, `azure_sys`, `postrgres`) are postgresql flexible databases which are created and maintained by the server itself. The error you saw above occured when calling `GET` on them, which seems the service team doesn't allow users to do so. As a result, users are expected to skip these 3 databases (via focusing them and press <kbd>delete</kbd>).

Regarding the skipped vnet, could you please paste the full resource id (via scale out your terminal...)?

**Comment by dermoritz** [comment]
My general problem / Question is: how useful the TF output is for Psotgres? Why it is creating some hundred resources for one Postgres Server? 
If i look at the [Postgres Terraform Doku](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server) i do not need to cretae some hundred resources. Should the out put of aztfy not similar to this. With this many resources, and the need to ignore delete some of them - the out put is barely usable?!

**Comment by magodo** [comment]
@dermoritz Unfortunately, the output is not always as expected. As we are querying Azure resources and converting them to HCL, when we met some identified Azure resource, which has the corresponding TF resource type matched, we convert it.

In your case, there are a lot of default resources (those 3 databases and hundreds config resources) implicitly created by the PG RP team. We are currently not smart enough to distinguish between these default resource and the user managed resource. There isn't an easy approach to resolve this. One way to do is users that have the business background can manually filter out those default resources (e.g. save the mapping file, using `jq` to filter out the expected resources to import, then use `aztfy resmap`).

**Comment by dermoritz** [comment]
@magodo thanks for the detailed answer. I think i understand :-). I will filter out Postgres and create manually. In fact i added one Postgres Flexible Server Resource.
It might be helpful to get rid of theses 400?!

I might open another ticket regarding the skipped vnet resource if i play around with aztfy again.

**Comment by magodo** [comment]
@dermoritz It is indeed not friendly for users to manually filter these resources, as there is no clear document anywhere telling which resources are managed by who. For this same reason, it is a non-trivial effort for the tool to distinguish and skip them. Though we can reach to the RP team to ask the full list of the PG config/database, whilst that list might change later, which makes it hard to maintain. Furthermore, there are hundreds of Azure resource types...
