### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by John-Donalson** [Azure/aztfy#315]
Unable to copy exact text, but as executing against a RG, getting exit code 1 cannot connect to terraform registry; afterwards when trying to aztfy specific RG, starts to list resources and skips to command line on both interactive and --non. all other RGs in subscription work, only 2 (out of 8) specifically this occurs with. Nothing I can notice in common or out of place...

**Comment by magodo** [comment]
@John-Donalson Thank you for submitting this!

For *cannot connect to terraform registry*, this is an error from `terraform` itself, usually indicates the network problem when connecting to the terraform registry.

For *starts to list resources and skips to command line*, can you please run it with `--log-path <path2log>`, and attach the log here so that I can further investigate?

**Comment by John-Donalson** [comment]
log attached 
[log.txt](https://github.com/Azure/aztfy/files/10127388/log.txt)

again only on two resource groups out of the subscription...

**Comment by magodo** [comment]
@John-Donalson The logs look good to me, it just stops after listing the resources via ARG. Do you see anything output from the command line?

**Comment by John-Donalson** [comment]
negative; command line goes blank back to prompt and only a provider file, tf directory are made (no main.tf, etc generated)

**Comment by John-Donalson** [comment]
so i dont get the interactive option to import, if i use -n -k, same thing lists reaources then crashes back to prompt and nothing is actually generated in the directory.

**Comment by magodo** [comment]
@John-Donalson *crash back*, do you mean there is some panic log printed in the terminal? Would you mind provide a screen shot?

**Comment by magodo** [comment]
@John-Donalson We didn't instrument too much information in the log at this moment, I plan to add more logs in the future to make the log helpful. Right now, are you able to debug the tool to see when it was quit? From the log, it entered: https://github.com/magodo/azlist/blob/005f5e4c380423ea88b796aa138400d73d65adc0/azlist/azlist.go#L75, but didn't see any log which are expected to print from https://github.com/magodo/azlist/blob/005f5e4c380423ea88b796aa138400d73d65adc0/azlist/azlist.go#L91.

**Comment by magodo** [comment]
@John-Donalson I've made a PR (#317) to add more logs to `aztfy`, do you want to check it out and run again?

**Comment by John-Donalson** [comment]
going to rerun this again and try to debug; this is only on my latin america/asia subscriptions as well; going to try to log what happens with the four total resource groups that have this issue

**Comment by John-Donalson** [comment]
![crash](https://user-images.githubusercontent.com/113437897/205049497-c25b85a5-bd76-4574-b719-109e578e7ee7.PNG)
here is how the prompt looks after log,log1,log 2... 
[log.txt](https://github.com/Azure/aztfy/files/10132217/log.txt)
[log1.txt](https://github.com/Azure/aztfy/files/10132218/log1.txt)
[log2.txt](https://github.com/Azure/aztfy/files/10132219/log2.txt)


and here is log3.txt where I get the exit code again 
[log3.txt](https://github.com/Azure/aztfy/files/10132220/log3.txt)
![crash1](https://user-images.githubusercontent.com/113437897/205049675-4ab8a742-dc13-4d8b-969f-5987dbf7e4b9.PNG)

**Comment by magodo** [comment]
@John-Donalson The first picture indicates you are still in aztfy's TUI. The second picture indicates a network problem on your environment.

**Comment by John-Donalson** [comment]
deleting logs due to contents of ip data though. thanks :/ sorry couldnt provide more useful errors
