### ISSUE TITLE
Hcl-only option should allow for non-empty folders

### ISSUE THREAD

**Issue by cveld** [Azure/aztfy#339]
**Current behavior**
When I run with the `--hcl-only` flag e.g.
`aztfy resource --hcl-only --name iptable -n -o aztfy /subscriptions/someguid/resourceGroups/rg-platform-connectivity-ipgroups-prd-weu-001/providers/Microsoft.Network/ipGroups/ipgr-onprem-prd-weu-001`

and the folder is non-empty, currently `aztfy` yields the following error:

```
Error: the output directory "C:\\mypath\\Projects\\2022-11 Firewall\\aztfy" is not empty
```
(should the double backslash be unescaped in the console output?)

Also including the `--append` flag is currently not supported. `--append` only works without `--hcl-only`.

**Desired behavior**
Aztfy should just create a new hcl tf file in the same folder, or append to an existing file.

```
aztfy --version
aztfy version v0.9.0(a3341dd)
```

**Comment by magodo** [comment]
@cveld Thank you for raising this! The flag `--hcl-only` is a confusing flag, though it sounds like `aztfy` only export the configuration and not touch anything else, whilst the fact is that it will do the same process as `--hcl-only` is not specified, but after all that, it will remove everything under the output directory, only keep the hcl files. See #246.

That is also why we don't allow it to be used together with `--append`.

**Comment by magodo** [comment]
@cveld I'm gonna close this issue for now. Please feel free to reopen if you still have concerns.
