### ISSUE TITLE
Error: retrieving subscription id from CLI: failed to run azure cli: exit status 1

### ISSUE THREAD

**Issue by letmetechyou** [Azure/aztfy#354]
I get this error when trying to use the aztfy rg command even when logged in to my azure subscription

**Comment by magodo** [comment]
@letmetechyou The command used to retrieve the subscription id from CLI is `az account show --output json --query -id`. If the CLI version you used doesn't support that yet (the recent CLI version should however), you can instead specify the subscription id via `-s`.

**Comment by letmetechyou** [comment]
i was able to set the env variable via powershell in the cli ahead of time.
