### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by motti94** [Azure/aztfy#366]
Hi,

I'm using the last version of aztfy and Azure CLI on my mac.
I have Owner permission on the Azure subscription level.
I'm trying to export some Azure resources.
Please find below my steps-
1. az login
2. az account set --subscription="xxxxxxxxxxxxxxxxxxx"
3. aztfy rg test
4. Once trying to import (w) I'm getting an error-
![image](https://user-images.githubusercontent.com/92530574/222162330-0ad645b1-4468-41bf-86ea-2ac279d70763.png)

I tried everything possible, uninstalling and reinstalling, upgrading, etc but nothing is helping.
I even tried to export one Azure resource only.
I would very much appreciate your urgent input\assistance on this matter. 

Thanks in advance,
Motti.

**Comment by magodo** [comment]
@motti94 Unfortunately, this is an issue on azure CLI when your tenant has CAE enabled. Probably you can follow this workaround: https://github.com/Azure/azure-cli/issues/24684#issuecomment-1434443361, or you can try use other auth methods like client ID + client secret instead.

**Comment by motti94** [comment]
Thank you for your reply @magodo.
The workaround that you suggested didn't work for me.
I found another way and it solved my issue, I removed my user from the MFA setting.
Do you know if there is an open issue\defect on the above?
Thank you very much for your support.
Motti.

**Comment by magodo** [comment]
@motti94 Unfortunately, I don't know such an issue. Since your issue has been solved, and we can do nothing at the `aztfy` side, shall I close the issue for now?
