### ISSUE TITLE
Ability to import on management group scope

### ISSUE THREAD

**Issue by dhoeric** [Azure/aztfy#60]
Azure Policy allows to assign the policy on management group level. 
Would be nice if aztfy could support this.

Reference: https://docs.microsoft.com/en-us/azure/governance/policy/overview#:~:text=The%20term%20scope%20refers%20to,resources%20in%20that%20resource%20group.

**Comment by dhoeric** [comment]
Thanks for sharing. I had went with `terraform import` + `terraform state show ...` on my current workflow. 
Seems `tfadd` is similar to the workflow in used, will take further look at this! :)

**Comment by magodo** [comment]
@dhoeric Since v0.6.0, there is a subcommand `aztfy resource <resource id>`. This terrafies a single resource by its azure resource id, which is able to terrafy a policy definition resource also.
