### ISSUE TITLE
aztfy some resources skipped

### ISSUE THREAD

**Issue by H-Nawaz** [Azure/aztfy#62]
When using aztfy the keyvault resource always gets skipped, is this resource type not supported to be imported ?

 /subscriptions/000000-0000-0000-000000000/resourceGroups/testrg1/providers/Microsoft.KeyVault/vaults/new-vm-kv01
  │ (Skip)
    💡/subscriptions/000000-0000-0000-000000000/resourceGroups/testrg1/providers/Microsoft.Network/virtualNetworks/test-vm-vnet
    azurerm_virtual_network.res-1

    💡/subscriptions/000000-0000-0000-000000000/resourceGroups/testrg1/providers/Microsoft.Network/virtualNetworks/test-vm-vnet/subnets/applica
    azurerm_subnet.res-2

    💡/subscriptions/000000-0000-0000-000000000/resourceGroups/testrg1

**Comment by magodo** [comment]
@H-Nawaz Per the README.md:

> For each resource, user is expected to input the Terraform resource type. Users can press `r` to see the possible resource type(s) for the selected import item (though this is not guaranteed to be 100% accurate).

`aztfy` has limited knowledge on the mapping from AzureRM resource id to Terraform resource type, if it is sure, it will automatically fill that in automatically, with a 💡 as an indicator.

**Comment by H-Nawaz** [comment]
@magodo thanks for responding,

You are right that the resource type is coming up with unknown.

When pressing r it is  showing as unknown resource type but does not allows me to specify it manually, how do I specify the resource type manually ?

**Comment by magodo** [comment]
@H-Nawaz 

1. Navigate the import list and select the item via <kbd>j</kbd>/<kbd>k</kbd>
2. Press <kbd>enter</kbd>
3. Typing (can press <kbd>tab</kbd> to auto-complete)
4. Press <kbd>esc</kbd>/<kbd>enter</kbd> once finished

**Comment by H-Nawaz** [comment]
Thanks @magodo, that indeed was it.
