### ISSUE TITLE
Unable to import Managed Disk

### ISSUE THREAD

**Issue by yukihonhk** [Azure/aztfy#77]
Unable to import Managed Disk. e.g. if the VM has 3 attached managed disks, only the OS disk can be imported.

**Comment by magodo** [comment]
@yukihonhk Thank you for submitting this! I'm wondering the symptom of the issue, is the import raise error, or something else?

**Comment by yukihonhk** [comment]
There is no error during "import" but I found the main.tf file does not include the "managed data disk attachment" for the VMs, is it by design?

**Comment by magodo** [comment]
@yukihonhk You shall ensure during the interactive stage, all the managed data disks are correctly mapped to the TF resource from their Azure resource ID, otherwise, they'll be skipped from importing.

**Comment by yukihonhk** [comment]
@magodo Thank you for your feedback. However, during the interactive stage, I can't see any managed data disks available for mapping to the TF resource (I can only see VM, network interface, etc but no managed disk resource). Attached the screen cap for your quick reference.
![Screenshot 2](https://user-images.githubusercontent.com/76507010/165415935-431601a7-88f8-48ef-bc91-86ac39e18bc7.jpg)
![Screenshot 3](https://user-images.githubusercontent.com/76507010/165415942-67b5a8d5-975e-455c-b946-528f203866a3.jpg)
![Screenshot 1](https://user-images.githubusercontent.com/76507010/165415943-bbb87b09-663c-46b0-b6e3-6fcb65c1deb1.jpg)

**Comment by magodo** [comment]
@yukihonhk Thank you for providing the details! This indicates the managed data disk is missing in the exported ARM template in this resource group scope. Would you please confirm this in Portal via exporting ARM template?

**Comment by yukihonhk** [comment]
@magodo  I can see the data disk in the ARM template. Attached the screen cap for your info.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/76507010/165427736-6b877543-9578-4442-bf10-19f70e646813.png">

**Comment by magodo** [comment]
@yukihonhk 👆 shows the managed disk is referenced by the VM, but didn't mean the exported ARM template includes the managed disk as a separate resource. In this case, the only way to  include them is via https://github.com/magodo/tfadd to manually import and generate config for it. Note that you have to manually add the dependency between the managed disk and the VM afterwards.
