### ISSUE TITLE
Error Parsing Keyvault Nested Item

### ISSUE THREAD

**Issue by jwmoss** [Azure/aztfy#86]
Hi! It appears that there's an issue parsing more than 2-3 segments of the keyvault arm template (AFAIK). Let me know if you need more context or logs.

![image](https://user-images.githubusercontent.com/2729151/167473621-e4016a23-f4a2-4c36-a1f7-ca8679ee9e73.png)

**Comment by Joerg-L** [comment]
We are hitting the same issue
