### ISSUE TITLE
aztfyResourceMapping.json only saves resources it mapped propperly

### ISSUE THREAD

**Issue by jeramec** [Azure/aztfy#90]
aztfy version: 0.3.0
terraform version: 1.1.9

After running a scan against a resource group, I have a large number of resources that didn't map correctly. Pressed **S** to save, which created the **aztfyResourceMapping.json** file, however it is only populated with the few resources that mapped correctly, as opposed to all resources.

**Comment by magodo** [comment]
@jeramec The resource map file is used to record the mapping from azure resource id to terraform resource address, based on what the mapping is at the point you pressed <kbd>S</kbd>. This means <kbd>S</kbd> doesn't mean to auto matically give you the correct mapping. `aztfy` currently is not smart enough to deduce the terraform resource address based on the input azure resource id (though it tries to do that and give some good guess for some IDs). Alternatively, you can select the item in the UI and press <kbd>R</kbd> to see whether there is some candidate resource type for the current active resource id.

**Comment by magodo** [comment]
@jeramec I think you mean this twit: https://twitter.com/JerameC/status/1524436406755549185. This is not a bug actually, it only saves the current mapping. Please note that *saving the mapping* is different than *deduce the mapping automatically* (which is done as a best effort, and you might try <kbd>R</kbd> to see whether there is any recommendation on the mapped Terraform resource type).

**Comment by jeramec** [comment]
Yeah, I understand that this will not resolve the mapping issue, that was meant to be an easy way to list all of the missing items that will need to be mapped.

I have a resource groups with Azure SQL Server/Database, Storage and Data Lake it it is only able to deduce 3 of the 36 items.

**Comment by magodo** [comment]
Sorry that `aztfy` is not smart enough to deduce these resources at the moment, we will do some enhancement on this part. But for the generated mapping file, it is delibrately ignoring the unmapped resources. This means the next time when you use this mapping file, all the absent items in the file, but shows up in the import list, will be ignored to import.
