### ISSUE TITLE
Update Azure Service Template

### ISSUE THREAD

**Issue by peterhee** [Azure/aztfy#97]
- Update Azure Service Template to align with Foundation update.
- remove Warning N-Tier Application Patterns IaaS and PaaS

**Comment by magodo** [comment]
@peterhee Would you please provide some links/documents about how to make these changes?

BTW, this repo is not a azure service, it is just a tool that calls Azure API (currently only one API called by itself, the `exportTemplate`).

**Comment by peterhee** [comment]
Sorry wrong thread – please ignore it.

Cheers

Peter Heese
Incubation Architect – Solution Architect Office | ***@***.******@***.***>
Desk:+49 (0) 89 3176 3821<tel:+441189092718> | Cell:+49 (0) 175 5844792<tel:+44>

Need time for a meeting? I live by my Outlook Calendar, it’s always up to date, albeit occasionally fluid at times, and there are normally a few available slots. So, if you need to meet to discuss a topic, then please use Outlook Free/Busy to find a free slot that also works for you and schedule something. Thank you.
 ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶

Planned Vacation
15th Apr – 19th Apr 2022

26th May – 20th June 2022

15th Aug 2022
 ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶ ̶

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.


From: magodo ***@***.***>
Date: Wednesday, 18. May 2022 at 08:06
To: Azure/aztfy ***@***.***>
Cc: Peter Heese ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/aztfy] Update Azure Service Template (Issue #97)

@peterhee<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpeterhee&data=05%7C01%7CPeter.Heese%40microsoft.com%7C5a4be4265b984e5a38a408da389479e6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637884507616212468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oKWHYNu0BnCF4R%2B6R27OFe1nBlVLMkIOr72fOJRXRUM%3D&reserved=0> Would you please provide some links/documents about how to make these changes?

BTW, this repo is not a azure service, it is just a tool that calls Azure API (currently only one API called by itself, the exportTemplate).

**Comment by peterhee** [comment]
Please close the issue - the comment was for another repository. Sorry Peter
